apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: lovable-core
spec:
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: CONFIG_SERVER_URL
              value: "{{ .Values.configServer.url }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
