FROM eclipse-temurin:21-jre

WORKDIR /app

COPY target/workspace-service-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]FROM eclipse-temurin:21-jre

WORKDIR /app

COPY target/workspace-service-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
